project: RL_final_mapping
name: transformer
seed: 0

data:
    batch_size: 64
    domain1_base_path: "~/RL_2023_Fall/mapping/data/density250"
    domain2_base_path: "~/RL_2023_Fall/mapping/data/density1000"

train:
    lr: 0.0001
    weight_decay: 0.00005
    device: "cuda:0"
    epoch: 1000

model:
    input_dim: 20
    hidden_dim: 128
    output_dim: 20
    layer: 10
    dim_head: 64
    n_head: 8
    dropout: 0.25

enable_wandb: True
