project: RL_final_mapping
name: transformer
seed: 0

data:
    batch_size: 32
    domain1_base_path: "~/RL_2023_Fall/mapping/data/density250"
    domain2_base_path: "~/RL_2023_Fall/mapping/data/density1000"

train:
    lr: 0.0001
    weight_decay: 0.00005
    device: "cuda:0"
    epoch: 2000

model:
    input_dim: 20
    hidden_dim: 64
    output_dim: 20
    layer: 5
    dim_head: 32
    n_head: 4
    dropout: 0.0

enable_wandb: True
