defaults:  
    - _self_  
    - override hydra/hydra_logging: disabled  
    - override hydra/job_logging: disabled  
  
hydra:  
    output_subdir: null  
    run:  
        dir: .

project: RL_final_mapping
name: transformer
seed: 0

data:
    batch_size: 32
    domain1_base_path: "data/density250"
    domain2_base_path: "data/density1000"

train:
    lr: 0.0001
    weight_decay: 0.00005
    device: "cuda:0"
    epoch: 2000
    save_path: "checkpoint"

model:
    input_dim: 20
    hidden_dim: 64
    output_dim: 20
    layer: 5
    dim_head: 32
    n_head: 4
    dropout: 0.0

enable_wandb: True
